const mainStyles = {
  internalMainContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    justifyContent: "flex-start",
    width: "85%",
    maxWidth: "1440px",
  },

  helpButtonContainer: {
    width: "100%",
    display: "flex",
    justifyContent: "flex-end",
    alignItems: "center",
    height: "60px",
  },
  helpText: {
    marginLeft: "10px",
    color: "#731054",
    fontSize: "14px",
    fontWeight: "400",
  },
  clientSectionContainer: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
  },
  clientsHeaderText: {
    fontSize: "20px",
    color: "#040404",
    fontWeight: "700",
  },
  filtersMainContainer: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
    marginTop: "24px",
    marginBottom: "16px",
    gap: "10px",
  },
  formControl: {
    width: { xs: "100%", md: "300px" },
  },
  selectLabel: {
    width: "280px",
    textAlign: "start",
    fontSize: "12px",
    fontWeight: "500",
    color: "#000",
    marginBottom: "8px",
  },
  textField: {
    height: "40px",
    borderColor: "#fff",
    borderRadius: "8px",
    backgroundColor: "#fff",
  },
  divider: {
    height: "1px",
    width: "46%",
    marginTop: "24px",
  },
  addClientButton: {
    marginLeft: "auto",
    textTransform: "none",
    borderColor: "#731054",
    color: "#731054",
    minWidth: "170px",
    width: "190px",
    height: "40px",
    fontSize: "16px",
    marginTop: "24px",
  },
  tableContainer: {
    marginTop: "16px",
    backgroundColor: "#fff",
    paddingLeft: "8px",
    borderRadius: "8px",
  },
  tableHeader: {
    fontWeight: "700",
    fontSize: "14px",
    textAlign: "left",
    padding: "8px",
  },
  tableRow: {
    padding: "8px",
    fontSize: "14px",
  },
  clientType: {
    padding: "2px 8px",
    borderRadius: "4px",
    color: "#000",
    fontSize: "12px",
  },
  modalSubContainer: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    width: "528px",
    maxHeight: "90vh",
    overflowX: "hidden",
    overflowY: "auto",
    bgcolor: "background.paper",
    borderRadius: "10px",
    boxShadow: 24,
    padding: "2%",
  },
  modalCloseIcon: {
    position: "absolute",
    right: "25px",
    top: "20px",
    cursor: "pointer",
  },
  mandatoryField: {
    color: "red",
  },
  modalHeader: {
    fontSize: "20px",
    fontWeight: "700",
    marginBottom: "16px",
    color: "#333",
    width: "100%",
    textAlign: "center",
  },
  modalSection: {
    marginBottom: "12px",
    width: "100%",
    textAlign: "center",
    color: "#707070",
    fontSize: "14px",
    fontWeight: "400",
  },
  radioButton: {
    color: "#731054",
  },
  switchContainer: {
    display: "flex",
    alignItems: "center",
    width: "100%",
    justifyContent: "space-between",
    marginBottom: "16px",
  },
  buttonContainer: {
    width: "100%",
    display: "flex",
    justifyContent: "flex-end",
  },
  buttonStyle: {
    marginTop: "16px",
    minWidth: "110px",
    backgroundColor: "#731054",
    color: "white",
    textTransform: "none",
  },
  noDataContainer: {
    textAlign: "center",
    padding: "20px",
    width: "100%",
  },
  noDataText: {
    fontSize: "14px",
    color: "#040404",
  },
};

export { mainStyles };
